name: Chart-Preparation-With-Pre-Commit

on:
  pull_request:
    types: [opened, reopened]
  push:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          check-latest: true
      - run: python --version
      - uses: pre-commit/action@v3.0.1
